### ISSUE TITLE
Decoding both success and client error response bodies

### ISSUE THREAD

**Issue by vecerek** [contactlab/appy#322]
**Is your feature request related to a problem? Please describe.**
Hello, first of all, I think `appy` is really great! I like the modularity and extensibility it provides 🙂 I have just started experimenting with the library and I have several questions and probably a feature request as well. But first, let me describe my use case.

I want to be able to provide one or more decoders, so that different responses can be decoded. I'd prefer the single decoder option with a tagged union:
```ts
type DecodedResponse = 
| { status: 200; data: { ... }, response: Response }
| { status: 400; data: { ... }, response: Response }
```

With `status` being the tag, consumers could write switch statements to execute different branches depending on the response status. The library provides a `withDecoder` combinator but currently, it only decodes success responses, not client errors. It also forcefully sets the accept and content-type headers. May I ask what has driven this design decision? 🙂 

I can also see that the library is currently depending on fetch being accessible as a global. I find this a bit inconvenient in my current use case(s). I would like to use appy mostly to write HTTP client libraries each being specific to a single service. With this approach, each library has to make sure that fetch, Headers, Response, etc. are all available as globals. That's a lot of code duplication not mentioning that the services depending on these wrappers may be outside of my control. If I decide to overwrite the globals every time, I run the risk that I break the services depending on my packages. If I decide not to overwrite the globals, I risk that my package won't work if the fetch defined as the global does not adhere to the expected API by `appy`. Would it be possible for appy to expect the consumers to provide their own implementations of fetch in the form of a dependency injection instead of relying on the globals?

**Describe the solution you'd like**

To make appy work with my current use case, I have implemented some custom combinators which, I think, could be valuable additions to this library. I'll share the code I've come up with here:

```ts
// with-parsed-error-body.ts

import * as RTE from "fp-ts/lib/ReaderTaskEither";
import * as TE from "fp-ts/lib/TaskEither";
import { pipe } from "fp-ts/lib/pipeable";
import { Err, Req, Resp, toResponseError } from "@contactlab/appy";

const parseResponse = <A>(resp: Resp<A>): TE.TaskEither<Error, A> =>
  TE.tryCatch<Error, A>(
    async () => {
      if (typeof resp.data === "object") {
        return resp.data;
      }

      const contentType = resp.response.headers.get("Content-Type");
      if (contentType === "application/json") {
        return await resp.response.json();
      }

      return await resp.response.text();
    },
    reason => {
      if (reason == undefined) {
        return new Error("Unknown error");
      }

      return reason instanceof Error ? reason : new Error(String(reason));
    }
  );

export const withParsedErrorBody = <A>(): ((req: Req<A>) => Req<A>) => req =>
  pipe(
    req,
    RTE.chain(resp =>
      RTE.fromTaskEither(
        pipe(
          parseResponse(resp),
          TE.bimap(
            (e): Err => toResponseError(e, resp.response),
            data => ({ ...resp, data })
          )
        )
      )
    )
  );
```

The above combinator parses both a success response and the error response, if possible. Depending on the content-type response header, it either parses the response body as a JSON, or as plaintext. If parsing fails for any reason, TE resolves to a left with an Error as the value.

```ts
// with-decoder.ts

import { Err, Req, Resp, toResponseError } from "@contactlab/appy";
import { Decoder, toDecoder } from "@contactlab/appy/combinators/decoder";
import * as t from "io-ts";
import { failure } from "io-ts/lib/PathReporter";
import * as E from "fp-ts/lib/Either";
import { pipe } from "fp-ts/lib/pipeable";
import * as RTE from "fp-ts/lib/ReaderTaskEither";

export const fromIots = <A>(d: t.Decoder<unknown, A>): Decoder<A> =>
  toDecoder(d.decode, e => new Error(failure(e).join("\n")));

const parseResponse = <A>({ data, response: { status } }: Resp<A>): E.Either<Error, unknown> => {
  if (data !== undefined && typeof status === "number") {
    return E.right({ data, status });
  }

  const asString = String(data);
  const prepared = asString.length === 0 ? "{}" : asString;

  return E.parseJSON(prepared, E.toError);
};

export const withDecoder = <A, B extends { data: unknown; status: number }>(
  decoder: t.Decoder<unknown, B>
): ((req: Req<A>) => Req<B>) => req =>
  pipe(
    req,
    RTE.chain(resp =>
      RTE.fromEither(
        pipe(
          parseResponse(resp),
          E.chain(fromIots(decoder)),
          E.bimap(
            (e): Err => toResponseError(e, resp.response),
            data => ({ ...resp, data })
          )
        )
      )
    )
  );
```
The above `withDecoder` expects a decoder in the shape of the tagged union I previously described. `parseResponse` expects a `data` object in the response, so it's important to chain `withDecoder` after `withParsedErrorBody`.

An example of some consumer code:
```ts
import { post } from "@contactlab/appy";
import { withDecoder } from "./with-decoder"
import { withParsedErrorBody } from "./with-parsed-error-body";

...
const OkResponseCodec = t.type({
  status: t.literal(200),
  data: t.type({ a: t.string }),
});
const BadRequestResponseCodec = t.type({
  status: t.literal(400),
  data: t.type({
    errors: t.array(t.type({
      code: t.string,
      title: t.string,
    }))
  }),
});
const ResponseCodec = t.union([
  OkResponseCodec,
  BadRequestResponseCodec
]);

const req = pipe(
  post,
  withHeaders({
    Accept: "application/json",
    "Content-Type": "application/json",
    ...additionalHeaders,
  }),
  withBody(body),
  withTimeout(timeout),
  withParsedErrorBody(),
  withDecoder(ResponseCodec)
)(url.href);

const response = await req();

return pipe(
  response,
  E.fold(
    ({ error }) => E.left(error),
    ({ data: { status, data }, response }) => {
      switch(status) {
        case 200:
          console.log(data.a);
          break;
        case 400:
          console.log(data.errors);
          break;
      }
    }
  )
)
```

**Describe alternatives you've considered**

**Additional information/context**

More ideas for combinators:
- `withRetry`
- `withCircuitBreaker`

**Comment by vecerek** [comment]
I've just discovered that the above still doesn't work because appy throws on "non-ok" responses: https://github.com/contactlab/appy/blob/e77bb0de7c9396b2a7accbe3d285e2a7c96bfc0d/src/index.ts#L116-L121.

**Comment by StefanoMagrassi** [comment]
hello @vecerek, what a huge issue!

> I want to be able to provide one or more decoders, so that different responses can be decoded. I'd prefer the single decoder option with a tagged union [...] May I ask what has driven this design decision? 

Yes, it was a design decision. There are at least 2 ways to deal with resource fetching:

1. handling responses when request is "prepared" (like [`fetcher-ts`](https://github.com/YBogomolov/fetcher-ts) does - which is closer to your needs);
2. handling responses when request is "executed".

We choose the second option, because we thought that this solution is more flexible.
So, we modeled the types in order to be as simpler as possible, using tools or definition already available: `Request` and `Response` from standard fetch API, `Either` and `TaskEither` from `fp-ts` in order to handle successes and failures.

And this lead us to:
>  I can also see that the library is currently depending on fetch being accessible as a global. I find this a bit inconvenient in my current use case(s). I would like to use appy mostly to write HTTP client libraries each being specific to a single service. With this approach, each library has to make sure that fetch, Headers, Response, etc. are all available as globals. That's a lot of code duplication not mentioning that the services depending on these wrappers may be outside of my control. If I decide to overwrite the globals every time, I run the risk that I break the services depending on my packages. If I decide not to overwrite the globals, I risk that my package won't work if the fetch defined as the global does not adhere to the expected API by appy. Would it be possible for appy to expect the consumers to provide their own implementations of fetch in the form of a dependency injection instead of relying on the globals?

The idea behind `appy` is to be a wrapper around standard fetch API in order to increase type safety and composability, without sacrificing interoperability with existing code.

So, global `fetch` **is** a requirement, as specified in the [docs](https://github.com/contactlab/appy#about-fetch-compatibility).

Being compliant with a spec makes our code more robust.

BTW, the idea of providing a specific instance of `fetch` (the standard global one or a different implementation) is good and we could work on it.

About the combinators you provided, I have some hints:
- the `response.json()` method returns a `Promise<any>` which is _evil_;
- `io-ts` should not be a dependency of `appy`;
- making a generic function/combinator to work with tagged union based on response's status codes seems quite complicated; maybe you can write a function which works with `TaskEither` and handles the `ResponseError` on the `Left` side.

**Comment by StefanoMagrassi** [comment]
@vecerek can we also close this issue (somehow related to the PR #325)?
