### ISSUE TITLE
Wrong headers definition in withDecoder

### ISSUE THREAD

**Issue by DrugoLeB** [contactlab/appy#328]
**Is your feature request related to a problem? Please describe.**
Inside the `withDecoder` combinator is used the `withHeaders` to inject automatically the headers:
- `Accept: application/json`
- `Content-Type: application/json`

The ratio is clear and it's to indicate to a backend service the needs of a JSON-like response body to be decoded. Actually, this need is indicated using the `Accept` request header, as described by https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept.

Therefore, the `Content-Type: application/json` that is injected automatically ends to be useless since a request can be sent also with other types of data that should/could be defined by the end-user. Moreover, it can also be a source of bugs if it's put at the end of a functional pipeline, as in the following example:

```typescript
pipe(
  request,
  withHeaders({ 
    'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'
  }),
  withDecoder(codec),
)
```

**Describe the solution you'd like**

The solution I thought is pretty simple: removing the `Content-Type` from the `withHeaders` combinator used inside `withDecoder` combinator moving the responsibility of setting the media type with `Content-Type` to the end-user.

**Comment by StefanoMagrassi** [comment]
@DrugoLeB thank you for your hint.

I changed the tag of the issue into "bug" because, as you pointed out, the `Content-Type` header on request side can be other than `application/json` and a different value provided by the user could be wrongly overriden
